//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.12.26 at 05:54:18 PM IST
//
package com.gao.core.framework.repository.workspace.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FileSystem" type="{http://www.example.org/Workspace}FileSystem"/>
 *         &lt;element name="PersistenceManager" type="{http://www.example.org/Workspace}PersistenceManager"/>
 *         &lt;element name="SearchIndex" type="{http://www.example.org/Workspace}SearchIndex"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileSystem",
    "persistenceManager",
    "searchIndex"
})
@XmlRootElement(name = "Workspace")
public class Workspace {

    @XmlElement(name = "FileSystem", required = true)
    protected FileSystem fileSystem;
    @XmlElement(name = "PersistenceManager", required = true)
    protected PersistenceManager persistenceManager;
    @XmlElement(name = "SearchIndex", required = true)
    protected SearchIndex searchIndex;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the fileSystem property.
     *
     * @return
     *     possible object is
     *     {@link FileSystem }
     *
     */
    public FileSystem getFileSystem() {
        return fileSystem;
    }

    /**
     * Sets the value of the fileSystem property.
     *
     * @param value
     *     allowed object is
     *     {@link FileSystem }
     *
     */
    public void setFileSystem(FileSystem value) {
        this.fileSystem = value;
    }

    /**
     * Gets the value of the persistenceManager property.
     *
     * @return
     *     possible object is
     *     {@link PersistenceManager }
     *
     */
    public PersistenceManager getPersistenceManager() {
        return persistenceManager;
    }

    /**
     * Sets the value of the persistenceManager property.
     *
     * @param value
     *     allowed object is
     *     {@link PersistenceManager }
     *
     */
    public void setPersistenceManager(PersistenceManager value) {
        this.persistenceManager = value;
    }

    /**
     * Gets the value of the searchIndex property.
     *
     * @return
     *     possible object is
     *     {@link SearchIndex }
     *
     */
    public SearchIndex getSearchIndex() {
        return searchIndex;
    }

    /**
     * Sets the value of the searchIndex property.
     *
     * @param value
     *     allowed object is
     *     {@link SearchIndex }
     *
     */
    public void setSearchIndex(SearchIndex value) {
        this.searchIndex = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }
}
